### ISSUE TITLE
Django 1.8 TEMPLATE_DEBUG deprecation warning

### ISSUE THREAD

**Issue by wacax** [heroku/heroku-django-template#26]
I get the following warning with the template.

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.

It's nothing serious, and can be easily solved with this
https://stackoverflow.com/questions/32445953/django-app-works-fine-but-getting-a-template-warning-message

**Comment by kennethreitz** [comment]
Fixed!

**Comment by aviaryan** [comment]
I just cloned this repo today and I am still getting this error.

```
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
Operations to perform:
  Apply all migrations: contenttypes, auth, sessions, admin
Running migrations:
  No migrations to apply.
```

As a result, `hello_greeting` table is not created.

**Comment by aviaryan** [comment]
Sorry the above is an issue of github.com/heroku/python-getting-started
